Added warmup service and ping service

diff --git a/Docker/bootstrap b/Docker/bootstrap
--- a/Docker/bootstrap
+++ b/Docker/bootstrap
@@ -15,6 +15,19 @@ else
     make start_spamdetect &
     echo "### Starting CoffeeHouse-CoreNLP ###"
     make start_corenlp &
+    echo "### Starting CoffeeHouse-NSFW ###"
+    make start_nsfw &
+
+    echo "### Checking Service Status ###"
+
+    if ! python3 scripts/warmup.py; then
+      echo "ERROR: Some services failed to start successfully duing the warmup process"
+      exit 1
+    fi
+
+
+    echo "### Starting Ping Service ###"
+    make start_ping &
 
     while sleep 60; do
 
@@ -35,11 +48,26 @@ else
         exit 1
       fi
 
+      ps aux | grep coffeehouse_nsfw | grep -q -v grep
+      NSFW_STATUS=$?
+      if [ $NSFW_STATUS -ne 0 ]; then
+        echo "ERROR: coffeehouse_nsfw has been terminated, terminating container."
+        exit 1
+      fi
+
+      ps aux | grep coffeehouse_ping | grep -q -v grep
+      PING_STATUS=$?
+      if [ $PING_STATUS -ne 0 ]; then
+        echo "ERROR: coffeehouse_ping has been terminated, terminating container."
+        exit 1
+      fi
+
       ps aux | grep edu.stanford.nlp.pipeline.StanfordCoreNLPServer | grep -q -v grep
       CORENLP_STATUS=$?
       if [ $CORENLP_STATUS -ne 0 ]; then
         echo "ERROR: coffeehouse_corenlp has been terminated, terminating container."
         exit 1
       fi
+
     done
 fi
