Updated Docker

diff --git a/Docker/bootstrap b/Docker/bootstrap
--- a/Docker/bootstrap
+++ b/Docker/bootstrap
@@ -13,6 +13,8 @@ else
     make start_langdetect &
     echo "### Starting CoffeeHouse-SpamDetect ###"
     make start_spamdetect &
+    echo "### Starting CoffeeHouse-CoreNLP ###"
+    make start_corenlp &
 
     while sleep 60; do
 
@@ -30,6 +32,13 @@ else
       SPAMDETECT_STATUS=$?
       if [ $SPAMDETECT_STATUS -ne 0 ]; then
         echo "ERROR: coffeehouse_spamdetection has been terminated, terminating container."
+        exit 1
+      fi
+
+      ps aux | grep edu.stanford.nlp.pipeline.StanfordCoreNLPServer | grep -q -v grep
+      CORENLP_STATUS=$?
+      if [ $CORENLP_STATUS -ne 0 ]; then
+        echo "ERROR: coffeehouse_corenlp has been terminated, terminating container."
         exit 1
       fi
     done
